apiVersion: v1
kind: Namespace
metadata:
  name: app-01
  labels:
    app: app-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-01
  namespace: app-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-01
  template:
    metadata:
      labels:
        app: app-01
    spec:
      containers:
      - name: app-01
        image: nginx:latest
        ports:
        - containerPort: 80
---
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-01
  namespace: default
spec:
  selector:
    app: app-01
  ports:
  - name: http
    targetPort: 80
    port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-app-01
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nginx-01.traefik.braga.me`)
      kind: Rule
      services:
        - name: nginx-app-01
          port: 80
      middlewares:
        - name: default-headers
  tls:
    secretName: trafic-braga-me-production-tls